name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@main
      - name: env
        run: bazel --version
      - name: Test on Windows
        if: matrix.os == 'windows-latest'
        run: bazel test --config=windows //test:tests
      - name: Test
        if: matrix.os != 'windows-latest'
        run: bazel test --config=osx //test:tests
