name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 6' # at 10:00 UTC every saturday

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install requests
      - name: Update
        run: python tools/update_tools_reg.py
      - name: Check if file changed
        id: check-changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update tools"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
